package badWeatherApp.serverUtility.responseCollector.forecast;

public enum ForecastMeasurement {
    TEMPERATURE_MIN,
    TEMPERATURE_MAX,
    TEMPERATURE_DAY,
    TEMPERATURE_NIGHT,
    TEMPERATURE_EVENING,
    TEMPERATURE_MORNING,
    FEELS_LIKE_TEMPERATURE_DAY,
    FEELS_LIKE_TEMPERATURE_NIGHT,
    FEELS_LIKE_TEMPERATURE_EVENING,
    FEELS_LIKE_TEMPERATURE_MORNING,
    WIND_SPEED,
    WIND_DIRECTION,
    PRESSURE,
    HUMIDITY
}
